import test from 'node:test'
import assert from 'node:assert/strict'
import { createState, step, perform, nearestAction, SITES, TRASH, CACHES, STATION, CAMP, SAVE_KEY, tide, isStorm, floorHeight, terrainHeight, restore, serialize, metrics, rescue } from '../src/action/simulation.js'
const move = (s, p) => Object.assign(s.player, { x:p.x, z:p.z, y:floorHeight(p.x,p.z), vy:0, grounded:true })
const advance = (s,input,seconds) => { for(let i=0;i<Math.round(seconds*60);i++)step(s,input,1/60) }
const supply = (s) => {move(s,CACHES[0]); assert.equal(perform(s,nearestAction(s)),true)}
const ready = () => {const s=createState();s.seeds=[3,3,3];return s}

test('action saves are separate; independent fresh objects',()=>{const a=createState(),b=createState();a.seeds[0]=3;assert.equal(b.seeds[0],0);assert.equal(SAVE_KEY,'mangrove-ranger-action-v1')})
test('fixed steps advance movement and normalize diagonal speed',()=>{const a=createState(),b=createState();advance(a,{z:1},.5);advance(b,{z:1,x:1},.5);assert.ok(Math.abs(Math.hypot(a.player.x,a.player.z-12)-Math.hypot(b.player.x,b.player.z-12))<.02)})
test('pause freezes time and position',()=>{const s=createState();const before=serialize(s);step(s,{z:1,paused:true},.05);assert.equal(serialize(s),before)})
test('sprinting spends stamina; resting recovers it',()=>{const s=createState();advance(s,{z:1,sprint:true},.5);assert.ok(s.player.stamina<95);advance(s,{},1);assert.equal(s.player.stamina,100)})
test('jump leaves ground and cannot retrigger while key remains held',()=>{const s=createState();step(s,{jump:true},1/60);assert.ok(s.player.y>floorHeight(s.player.x,s.player.z));advance(s,{jump:true},1.5);assert.equal(s.player.grounded,true);assert.equal(s.player.vy,0)})
test('fallen trunk blocks walking through it',()=>{const s=createState();move(s,{x:0,z:-4});advance(s,{z:1},1.5);assert.ok(s.player.z>-5.5)})
test('mud slows movement and drains stamina',()=>{const a=createState(),b=createState();move(a,{x:-6,z:-9});advance(a,{z:1},.3);advance(b,{z:1},.3);assert.ok(Math.abs(a.player.z+9)<Math.abs(b.player.z-12));assert.ok(a.player.stamina<100)})
test('tide varies and the raised bridge stays above high tide',()=>{assert.ok(tide(48)>tide(0));assert.ok(floorHeight(-10,-18)>tide(48));assert.ok(terrainHeight(0,-18)<tide(48))})
test('weather has warning-safe and storm phases',()=>{assert.equal(isStorm(100),false);assert.equal(isStorm(110),true);assert.equal(isStorm(135),false)})
test('no remote actions; supply is reusable and capped',()=>{const s=createState();assert.equal(perform(s,{id:'camp-cache',kind:'supply'}),false);supply(s);assert.deepEqual(s.seeds,[3,3,3]);supply(s);assert.deepEqual(s.seeds,[3,3,3])})
test('wrong species and empty inventory do not plant',()=>{const s=createState();move(s,SITES[0]);let t=nearestAction(s);assert.ok(t.blocked);assert.equal(perform(s,t),false);s.seeds=[3,3,3];s.selected=2;t=nearestAction(s);assert.ok(t.blocked);assert.equal(perform(s,t),false);assert.equal(s.sites[0].plantedAt,null)})
test('hold interaction plants once and spends exactly one seed',()=>{const s=ready();move(s,SITES[0]);advance(s,{interact:true},3);assert.notEqual(s.sites[0].plantedAt,null);assert.equal(s.seeds[0],2);assert.equal(metrics(s).planted,1)})
test('walking or releasing cancels partial interaction',()=>{const s=ready();move(s,SITES[0]);advance(s,{interact:true},.5);assert.ok(s.progress>0);step(s,{},1/60);assert.equal(s.progress,0);advance(s,{interact:true,z:1},.2);assert.equal(s.progress,0)})
test('debris must be cleared before planting; no duplicate cleanup',()=>{const s=ready();s.selected=1;move(s,SITES[1]);const t=nearestAction(s);assert.equal(t.kind,'clean');assert.equal(perform(s,t),true);assert.equal(s.cleaned.length,1);assert.equal(perform(s,t),false);assert.equal(perform(s,nearestAction(s)),true);assert.notEqual(s.sites[1].plantedAt,null)})
test('evidence requires growth; one sample per tree',()=>{const s=ready();move(s,SITES[0]);perform(s,nearestAction(s));assert.ok(nearestAction(s).blocked);s.time=30;assert.equal(perform(s,nearestAction(s)),true);assert.equal(s.samples,1);assert.equal(s.sites[0].sampled,true);assert.equal(nearestAction(s),null)})
test('entire campaign can be completed; credits cannot be issued twice',()=>{const s=ready();move(s,STATION);assert.ok(nearestAction(s).blocked);for(const t of TRASH){move(s,t);assert.equal(perform(s,nearestAction(s)),true)}for(const site of SITES){move(s,site);s.selected=site.species;assert.equal(perform(s,nearestAction(s)),true)}s.time=40;for(const site of SITES.slice(0,3)){move(s,site);assert.equal(perform(s,nearestAction(s)),true)}move(s,STATION);const t=nearestAction(s);assert.equal(t.kind,'verify');assert.equal(perform(s,t),true);assert.equal(s.verified,true);assert.equal(s.credits,6);assert.equal(perform(s,t),false);assert.equal(s.credits,6)})
test('rescue preserves ecological progress and evidence',()=>{const s=ready();move(s,SITES[0]);perform(s,nearestAction(s));s.cleaned=['t1'];rescue(s);assert.equal(s.player.x,CAMP.x);assert.equal(s.player.z,CAMP.z);assert.equal(metrics(s).planted,1);assert.equal(s.cleaned.length,1);assert.equal(s.player.health,100)})
test('deep water eventually returns exhausted ranger to safety',()=>{const s=createState();move(s,{x:26,z:-9});s.player.health=1;advance(s,{},1);assert.equal(s.rescues,1);assert.equal(s.player.x,CAMP.x)})
test('save round trip, malformed JSON, numeric validation and forged completion',()=>{const s=ready();move(s,SITES[0]);perform(s,nearestAction(s));const copy=restore(serialize(s));assert.equal(metrics(copy).planted,1);assert.deepEqual(copy.seeds,s.seeds);assert.equal(restore('{broken').time,0);s.player.x=Infinity;s.credits=999;s.verified=true;const safe=restore(serialize(s));assert.equal(safe.player.x,0);assert.equal(safe.verified,false);assert.equal(safe.credits,0)})
